### ISSUE TITLE
string replace

### ISSUE THREAD

**Issue by CurtisHumphrey** [firebase/blaze_compiler#38]
I tried writing a function like:
- isEmail(email): email == root.users.private[auth.uid].email.replace('.','') == email
and I'm pretty sure "replace" cases a problem but is supported by firebase (https://www.firebase.com/docs/security/api/string/replace.html)

So what am I doing wrong?

**Comment by tomlarkworthy** [comment]
Sorry there is some weirdness there.
1. There is an open bug on sanitation of params. So the param email is clashing with the .email
2. The other unexpected behavior is that string methods are not coerced. This is deliberate because people use some of the methods as names. So put a .val() after the email.

A working function is:
isEmail(emailp): root.users.private[auth.uid].email.val().replace('.','') == emailp

The coercion bug is here if you want to track it
https://github.com/firebase/blaze_compiler/issues/28

**Comment by CurtisHumphrey** [comment]
Yes, your version worked just fine. Thanks!
